services:
  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: verbose_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  cache:
    image: redis:6.2.7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

## Persist redis cache
#     volumes:
#       - ./redis-data:/data
#       - ./redis-conf:/usr/local/etc/redis/redis.conf
# volumes:
#   redis-data:
#   redis-conf:
